### ISSUE TITLE
Reactive Styles?

### ISSUE THREAD

**Issue by bgarchow** [arktosk/vue-jss-plugin#33]
Thank you for writing this plugin. I installed the plugin and created a very simple app. When ```app``` is rendered, its background color is blue as expected. Clicking on ```app``` updates```data``` property ```bgColor``` to red as expected but the background color of ```app``` remains blue. Are additional configuration options required for this to work or is it not possible with this plugin?
```
<template>
  <div id="app" :class="$classes.app"  @click="onClick"></div>
</template>

<script>
  export default {
    name: 'App',
    styles: {
      app: {
        width: 100,
        height: 100,
        backgroundColor: ({ bgColor }) => bgColor
      }
    },
    data() {
      return {
        bgColor: 'blue'
      }
    },
    methods: {
      onClick() {
        this.bgColor = 'red'
      }
    }
  }
</script>
```

**Comment by arktosk** [comment]
Hey, please provide the version of vue that you used alongside the plugin. The plugin was tested only with Vue@2.6.x, so when you are using different version, then will be very helpful to know the Vue veriosn when debugging.

**Comment by bgarchow** [comment]
Thank you for your reply. Vue version was 2.6.11 but I have since decided not to use JSS for my project.
